[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
remappings = ['solidity-bytes-utils/=lib/solidity-bytes-utils',
'@chainlink/contracts-ccip/=lib/ccip/contracts', 'chainlink-local/=lib/chainlink-local/', '@uniswap/v4-core/=lib/v4-core/]', 'forge-gas-snapshot/=lib/v4-core/lib/forge-gas-snapshot/src/', 'forge-std/=lib/v4-core/lib/forge-std/src/',  'solmate/=lib/v4-core/lib/solmate/', 'v4-core/=lib/v4-core/', 'v4-periphery/=lib/v4-periphery/' ]



solc_version = "0.8.26"
evm_version = "cancun"
viaIR = true


# See more config options https://github.com/foundry-rs/foundry/tree/master/config